# http://module-build.sourceforge.net/META-spec.html
name:         Text-OutdentEdge
version:      0.01
version_from: lib/Text/OutdentEdge.pm
installdirs:  site
author:       YAMASHINA Hio <hio@cpan.org>
abstract: remove indent chars.
license: perl
#requires:
build_requires:
  Test::More: 0
no_index:
  directory:
    - inc
    - t
    - example

distribution_type: module
generated_by: ExtUtils::MY_Metafile version 0.07, EUMM-6.17.
meta-spec:
  version: 1.2
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
